import Header from "../components/principal";
import Footer from "../components/footer";
import Head from "next/head";

export default function format({ children, title }){
    return(
        <div>
            <Head>
        <title>Nutriña{title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <Header></Header>
            <main>{children}</main>
            <Footer></Footer>
        </div>
    );
}