import Head from "next/head";
import React from "react";
import Navbar from "./indexCool";

export default function Layout({ children, title }) {
  return (
    <div>
      <Head>
        <title>Nutriña{title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <div className="md:flex min-h-screen relative">
        <Navbar />
        <div className="bg-white flex-1 p-8 text-black">{children}</div>
      </div>
    </div>
  );
}
